server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://phananh1310:phananh1310@cluster0.abpbn.mongodb.net/test
      database: travelwala
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1046892340746-7jpqku689ato3k2p7cjco1egjjq51pqd.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 817594649135435
            client-secret: fb015a61be3ed030f2f2516e71c86543
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,email,first_name,middle_name,last_name,name,verified,picture.width(250).height(250)

stripe:
  api_key: sk_test_51LIPOjC6tixmsEI6zcNqgOimJ0k8ISd85qRU5GhVLfSDlcLeBzUk4JcOtFb72JdzJWZvLi6XUvkZRYQu4giyK6hJ00xexJeZt1
